# Generated by Django 4.2 on 2023-07-31 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.TextField(blank=True, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passout_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passout Year'),
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.company')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='companies_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.company'),
        ),
    ]
