# Generated by Django 4.2 on 2023-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_company_customuser_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='companies_applied',
        ),
        migrations.AddField(
            model_name='customuser',
            name='companies_applied',
            field=models.ManyToManyField(to='display.company'),
        ),
    ]
