# Generated by Django 4.2 on 2023-08-10 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_remove_customuser_companies_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='updates',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
