# Generated by Django 4.2 on 2023-08-15 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_company_date_alter_updates_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='Check your Email')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
