# Generated by Django 4.2 on 2023-08-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='description',
            field=models.TextField(default='Please check your email for more information'),
        ),
    ]
